### ISSUE TITLE
Не может скачать много  фотографии на стене сообщества ВК разом

### ISSUE THREAD

**Issue by Saloniel1** [morovinger/vk4y#1]
Пробую скачать фотографии на стене сообщества 14000 фоток прогресс скачки доходит до конца вместо того чтоб создать архив скаченный он начинает скачку по новой и так со всеми где архив фотографий большой то есть я понял эта программа разом максимум качает тысяч 5-8 что больше она не может ответьте мне это или баг или так и есть надеюсь вы сделаите чтоб можно было качать много фотографий разом либо пусть программа разбивает если архив большой на два три архива по меньше а так все норм

**Comment by Saloniel1** [comment]
Программа vk4y полное дно ставлю скачать Фотографии на стене сообщества
8321 фотография и прога не может скачать а вернее когда прогресс доходит до 100 процентов он не может заархивировать столько фотографий и получается все зря нахер тогда такая прога если она качает только маленькие объёмы фотографий

**Comment by morovinger** [comment]
В инструкции написано про большие обьемы, при более чем 2к фото альбом нужно разбить программой https://vk.com/movephotos Переоптимизация и разбивка на куски автоматически сейчас не предпологается

**Comment by Saloniel1** [comment]
Мы точно говорим об одном и том же? ты мне ссылку скинул на Перенос фото 3.7 мне нахрен не надо переносить фото с другого контакта в свой, я говорю про vk4y https://morovinger.github.io/vk4y/ где можно качать фотографии, а не переносить, а эта Перенос фото 3.7 мне даром не нужна. Заранее извиняюсь если чем то обидел))

**Comment by morovinger** [comment]
не получится скачать слишком большой архив, браузер не позволит, так что разделите альбом
