### ISSUE TITLE
Ничего не найдено по этой ссылке

### ISSUE THREAD

**Issue by rizen93rus** [morovinger/vk4y#2]
Как говорится еще вчера работало, а сегодня стем же альбомом выдает такое "Ничего не найдено по этой ссылке"

**Comment by morovinger** [comment]
Я не смог это воспроизвести. Проверьте, может доступы изменились и\или попробуйте создать новый альбом и перенести туда фото через приложение [Vk movephotos](https://vk.com/movephotos) и затем только скачать
